# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp
#   labels:
#     myLebelName: webapp
#     realease: "0"
# spec:
#   containers:
#   - name: webapp
#     image: richardchesterwood/k8s-fleetman-webapp-angular:release0

# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp-0-5
#   labels:
#     myLebelName: webapp
#     realease: "0-5"
# spec:
#   containers:
#   - name: webapp
#     image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

# ---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template: #template is a pod template that defines the pods that will be created by the replica set
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1-arm64